#!/usr/bin/env bash
# Regenerate golden reference outputs from the upstream Java insvtools.
#
# The Java is the format authority; these outputs are what the Python port is
# tested against. Requires Docker. The upstream clone is never modified: it is
# copied into a scratch dir and built there.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UPSTREAM="${UPSTREAM:-$REPO_ROOT/../insvtools}"
GOLDEN="$REPO_ROOT/tests/golden"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

MAVEN_IMAGE=maven:3.9-eclipse-temurin-17
# Maven cache lives outside the repo and is owned by the invoking user, so the
# container (run as that user) can populate it and cleanup never hits root-owned
# files. Deleting it only costs a re-download.
M2_CACHE="${M2_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/insta360py-m2}"
DOCKER_AS_USER=(--user "$(id -u):$(id -g)" -e HOME=/tmp)

[ -d "$UPSTREAM/src" ] || { echo "upstream insvtools not found at $UPSTREAM" >&2; exit 1; }

echo "[*] Copying upstream to scratch (clone stays pristine)"
cp -r "$UPSTREAM/." "$WORK/src-java/"
rm -rf "$WORK/src-java/.git"

echo "[*] Building insvtools.jar in $MAVEN_IMAGE"
mkdir -p "$M2_CACHE"
docker run --rm "${DOCKER_AS_USER[@]}" \
    -v "$WORK/src-java":/work -v "$M2_CACHE":/m2 -w /work \
    "$MAVEN_IMAGE" mvn -B -q -Dmaven.repo.local=/m2 clean package -DskipTests

echo "[*] Running reference commands on sample.insv"
mkdir -p "$WORK/out"
cp "$REPO_ROOT/tests/resources/sample.insv" "$WORK/out/"

# The Java writes outputs into the *current* directory, so run from $WORK/out.
docker run --rm "${DOCKER_AS_USER[@]}" \
    -v "$WORK/src-java":/java -v "$WORK/out":/out -w /out \
    "$MAVEN_IMAGE" bash -c '
        set -e
        run() { java -jar /java/target/insvtools.jar "$@"; }
        run dump-meta sample.insv
        run decompose-meta sample.insv
        run extract-meta sample.insv
        run cut --end-time=1 sample.insv
    '

echo "[*] Collecting into $GOLDEN"
rm -rf "$GOLDEN"
mkdir -p "$GOLDEN"
cd "$WORK/out"
rm -f sample.insv insvtools.log
cp -a . "$GOLDEN/"
# Record what produced these, so staleness is detectable.
{
    echo "Generated by tools/refgen.sh"
    echo "upstream commit: $(git -C "$UPSTREAM" rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "maven image:     $MAVEN_IMAGE"
} > "$GOLDEN/PROVENANCE"

echo "[*] Done:"
ls -la "$GOLDEN"
